# Generated by Django 4.1.7 on 2023-08-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_proffesional_dob'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users_details',
        ),
    ]
