# Generated by Django 4.1.7 on 2023-08-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='user_details',
        ),
    ]
