# Generated by Django 4.1.7 on 2023-08-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_users_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usr',
        ),
        migrations.AlterModelTable(
            name='usr',
            table='Usr_details',
        ),
    ]
